spring.application.name=Palvi-Hotel

# Database Configuration (Supabase)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres.cdmelamqonaumvanpbfj}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:KtEV6t2XAV43k5UE}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configs

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.postgresql=DEBUG
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=U29tZVNlY3JldEtleUZvckpXVEF1dGhlbnRpY2F0aW9uT2ZQYWx2aUhvdGVsTWFuYWdlbWVudFN5c3RlbVNlY3VyZQ==
jwt.expiration=86400000
jwt.refreshExpiration=604800000



